"""empty message

Revision ID: 3e572394e2e2
Revises: 30bcde17482c
Create Date: 2022-07-28 11:30:23.117119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e572394e2e2'
down_revision = '30bcde17482c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'year')
    op.drop_column('category', 'month')
    # ### end Alembic commands ###
