"""empty message

Revision ID: c277ef680b69
Revises: 3e572394e2e2
Create Date: 2022-08-03 11:22:13.929892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c277ef680b69'
down_revision = '3e572394e2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
